---
title: "Arabesque: a web-based thematic flow mapping application"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{article_FOSS4G2021}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
author:
- name: Nicolas Roelandt
  affiliation: Univ. Gustave Eiffel/AME
- name: Françoise Bahoken
  affiliation: Univ. Gustave Eiffel/AME
- name: Grégoire Le Campion
  affiliation: CNRS/UMR Passages
- name: Laurent Jégou
  affiliation: Univ. Toulouse Jean Jaurès/UMR Lisst-Cieu
- name: Marion Maisonobe
  affiliation: CNRS/UMR Géographie-cités
- name: Etienne Côme
  affiliation: Univ. Gustave Eiffel/COSYS/GRETTIA
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  warning = FALSE
)
```

<!--
Notes:
# Reminders:
- abstract due date : 08/03/2021 - 800-1000 words
- informations: https://2021.foss4g.org/call-for-papers/academic.html
- 20 min presentation, 5 min question, 5 minutes room change : 30 minutes slots
- topics: Open Geospatial Software, Open GIScience
- FOSS4G 2019 presentation: https://media.ccc.de/v/bucharest-205-gflowiz-an-open-science-framework-to-analyze-and-geovisualize-networks-and-flow-datasets
- SAGEO 2019 proceedings: https://sageo2019.inrae.fr/actes/
- FOSDEM demo : https://archive.fosdem.org/2020/schedule/event/arabesque_a_geographic_flow_visualization_application/
-->

# Abstract (ENG)

_Arabesque_ is an application for the exploration and geovisualisation of origin-destination flows (or spatial networks),
developed within the framework of the Univ. Gustave Eiffel (ex.IFSTTAR)-funded research project _geographic flow visualisation (gflowiz)_
[geoflowiz](https://geoflowiz.hypotheses.org/), in collaboration with the CNRS.

It allows both the exploration and the filtering of OD data and their representation, with a strong emphasis on geographic
information layering and features's semiology. The key-objective is to propose an easy way to produce a modern cartography
(a geovisualisation) of thematic flows (e.g. bilateral flow volume), at several geographic scales, even from your own datasets.

[Arabesque](http://arabesque.ifsttar.fr/) allows flow mapping from a modern web browser like Mozilla or Chrome.Its development benefits from several well known open-source data-visualisation, mapping and geo-processing libraries (OpenLayers, d3, TurfJS) and build also upon well known open data-sets (OpenStreetMap, NaturalEarthData). 

A demonstration of _Arabesque_ will be offered during the conference.
The analysis of its functionalities will be compared with those of similar web applications—_Magrit_, _Kepler.gl_, _flowmap.blue_, _Tableau_, _Carto.db_ and _Flourish_—which will be compared on the same flow dataset, for a practical and empirical "validation" of its contributions.

# Keywords :

origin-destination matrix, complex matrix, spatial network, geoweb, flowmap, flow mapping.

# Abstract (FR)

Arabesque est une application d’exploration et de géovisualisation de flux origine-destination (ou de réseaux spatiaux),
développée dans le cadre du projet de recherche geographic _flow visualisation (gflowiz)_
[geoflowiz](https://geoflowiz.hypotheses.org/), financé par l'Université Gustave Eiffel (ex- IFSTTAR), 
en collaboration avec le CNRS.

Elle permet à la fois l'exploration et le filtrage des données numériques et leur spatialisation,
en accordant une importance à l'information géographique, à la sémiologie des flux et au rendu général.
L'objectif est de proposer la réalisation d'une cartographie moderne (une géovisualisation) et thématique
de flux (volume bilatéral de flux, par exemple), à différentes échelles, y compris à partir de son propre jeu de données.

[Arabesque](http://arabesque.ifsttar.fr/) permet de réaliser des cartes thématiques de flux depuis un navigateur web moderne tel que Mozilla ou Chrome.
Son développement s’appuie sur les technologiques actuelles, particulièrement sur les données et bibliothèques de visualisation et
de cartographie web adaptées (OpenLayers, d3, TurfJS, OpenStreetMap NaturalEarthData). 

Une démonstration sera proposée lors de la conférence. L'analyse de ses fonctionnalités
sera comparée à celles de web applications similaires—_Magrit_, _Kepler.gl_, _flowmap.blue_, _Tableau_, _Carto.db_ and _Flourish_. Toutes seront
confrontées sur un même jeu de données pour une "validation" pratique et empirique de ses apports.

# Mots-clés: 

matrice origine-destination, matrice complexe, réseau spatial, geoweb, carte de flux, cartographie de flux.
