---
title: "Arabesque: a web-based thematic flow mapping application"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{article_FOSS4G2021}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
author:
- name: Étienne Côme
  affiliation: Univ. Gustave Eiffel
- name: Françoise Bahoken
  affiliation: Univ. Gustave Eiffel/AME
- name: Nicolas Roelandt
  affiliation: Univ. Gustave Eiffel/AME
- name: Laurent Jégou
  affiliation: Univ. Toulouse 2 Jean Jaurès/UMR LISST
- name: Grégoire Le Campion
  affiliation: CNRS/UMR Passages
  
  
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  warning = FALSE
)
```

<!--
Notes:
# Reminders:
- abstract due date : 08/03/2021
- informations: https://2021.foss4g.org/call-for-papers/academic.html
- 20 min presentation, 5 min question, 5 minutes room change : 30 minutes slots

- topics: Open Geospatial Software, Open GIScience
- FOSS4G 2019 presentation: https://media.ccc.de/v/bucharest-205-gflowiz-an-open-science-framework-to-analyze-and-geovisualize-networks-and-flow-datasets
- SAGEO 2019 proceedings: https://sageo2019.inrae.fr/actes/
- FOSDEM demo : https://archive.fosdem.org/2020/schedule/event/arabesque_a_geographic_flow_visualization_application/

<!--
Notes:
--> combien de signes (mots) pour le proceeding ?
--> Faut-il écrire en français ou en anglais ?
--> est-on limité par le nombre d'images ou d'illustrations ?
--> ce serait bien de préparer un exemple sur des jeux données. On prend lequel ?


# Abstract (ENG)

Arabesque is an application for the exploration and geovisualisation of origin-destination flows (or spatial networks), developed in the framework of the IFSTTAR-funded research project _geographic flow visualisation (gflowiz)_, in collaboration with CNRS.

It allows both the exploration and filtering of OD data and their representation, with a strong emphasis on geographic information layering and flow semiology. The objective is to propose a way to product a modern cartography (a geovisualisation) easily thematic flow maps (e.g. bilateral flow volume, for example), at several geographic scales, even from your own datasets.

([arabesque](http://arabesque.ifsttar.fr/) allows flow mapping from a web browser with Mozilla or Chrome.  Its development is based on current technological possibilities, in particular adapted web visualisation and mapping libraries (openlayers, d3, OSM, Turf, NaturalEarthData). 

# Keywords

origin-destination matrix, hyper matrix, spatial network, geoweb, flowmap, flow mapping.

# Abstract (fr)

Arabesque est une application d’exploration et de géovisualisation de flux origine-destination (ou de réseaux spatiaux), développée dans le cadre du projet de recherche geographic flow visualisation (gflowiz) financé par l'IFSTTAR, en collaboration avec le CNRS.

Elle permet à la fois l'exploration et le filtrage des données numériques que leur spatialisation,  en accordant une importante à l'information géographique, à la sémiologie des flux et au rendu général. L'objectif étant de proposer la réalisation d'une cartographie moderne (une géovisualisation) et thématiques de flux (ex. volume bilatéral de flux, par exemple), à différentes échelles, y compris à partir de son propre jeu de données.

([arabesque](http://arabesque.ifsttar.fr/) permet de réaliser des cartes thématiques de flux depuis un navigateur web équipé de Mozilla ou de Chrome. Son développement s’appuie sur les technologiques actuelles, particulièrement sur les bibliothèques de visualisation et de cartographie web adaptées (openlayers, d3, OSM, Turf, NaturalEarthData). 

# Mots-clés

matrice origine-destination, matrice complexe, réseau spatial, geoweb, carte de flux, cartographie de flux.

# Partie PAPIER / ACADEMIC PROCEEEDING


## Introduction 

bla bla bla





## Partie 1. Contexte - Etat de l'art


### Etat de l'art de la geoviz des flux et réseaux

Tobler (1979), The Flowmapper


### Analyse de notre corpus d'application
Les spécifications d'arabesque ont été rédigées après la constitution d'un d'un corpus de près de 80 applications permettant la visualisation de données de flux et réseaux spatiaux. Ces applications sont accessibles à partir d'un tableau de bord (Le Campion, Nguyen, 2019) proposant xxxxxx.

Une première analyse réalisée sur ce corpus (Bahoken et al., 2020) a mise en évidence trois grandes familles d'applications : i)xxxxxx ii) xxxxx et iii) xxxxx. 

==> Regarder si les applications présentent à la fois de l'analyse des données et des éléments de carto sémio. pour enrichir la carte. Quelle est leur part ?

Une enquête avait également menée en 2018 et 2019 sur les usages et les attentes de ce type d'application cartographique (Roelandt et. al, 2020). Les réponses apportée par les près de 200 répondants ont fait l'objet d'une première présentation lors du FOSS4G 2019^[https://media.ccc.de/v/bucharest-205-gflowiz-an-open-science-framework-to-analyze-and-geovisualize-networks-and-flow-datasets]. 

L'analyse du corpus d'applications collectées montre leur caractère "mono usage" et témoigne d'une déconnexion entre la représentation des flux en elle-même et les traitements réalisés en amont. Si ces derniers sont effectués en dehors de la cartographie proprement dite, ne pas en tenir compte est préjudiciable à l'image finale.

En effet, la majorité des applications recensées est limitée à la visualisation directe de flux, sans considérations des informations disponibles en amont de la représentations, qu'elles soient statistiques ou géographiques. Alors qu'en cartographie statistique générale, il est admis que les outils de représentation (magrit, Khartis, etc.) proposent  de discrétiser les données statistiques selon plusieurs méthodes ; de reprojeter les fonds de carte, voire d'en transformer l'implantation spatiale (par le passage d'entités aréales à des entités ponctuelles pour la réalisation de cartes lissées dans magrit, par exemple), rien de tel ou d'équivalent n'est proposé pour les données de flux, sauf dans de rares cas particulier (dans flowmap.blue, par exemple)

Et pourtant, des traitements statistiques ou géographiques de base sont nécessaires pour enrichir la carte. C'est le cas, par exemple, des propositions de décompositions des matrices de flux observées, souvent asymétriques, pour en représenter le volume, le solde bilatéral ou encore l'asymétrie de flux, correspondant respectivemet au "fondement du système d'échanges" ou à son "xxxxx " (Bertin, 1973 ; Tobler, 1979, 1982). De même qu'il est possible d'introduire quelques éléments devant permettre de prendre en compte la géographie des échanges, au niveau du rendu par la mise à disposition de couches d'informations permettant de contextualiser les échanges représentés et/ou lors du filtrage des données de flux par l'espace, c'est-dire selon une acception de la distance parcourue (kilométrique) ou de l'éloignement des OD par exemple. 

De plus, les fonctionnalités dédiées à la cartographie (choix et variété des figurés, actions sur leur géométrie, action sur leur symbologie) et à la sémiologie graphique des flux sont souvent réduites au minimun, à savoir au tracé d'un symbole linéaire (tracé d'un lien ou d'une flèche). Les aspects sémiologiques, pourtant essentiels dans la transmission du message cartographié sont dans bien des cas éludés ou réduits.

L'intérêt même de la cartographie statistique (dite thématique) de flux, qui résulte de l'articulation d'informations numériques et géographiques, toutes deux préparées en amont dans l'optique d'une représentation sensée (doté de sens et non limitée au seul affichage de couches d'information), ne semble pas pris en compte. Il en résulte une certaine pauvreté des images, au sens où elles sont limitées à une cartographie directe ; aussi à une forme d'homogénéité. C'est pourquoi arabesque se propose d'y remédier en réintroduisant les paradigmes de la cartographie (Mac Eachren, xxx)




## Partie 2. Présentation de Arabesque

Cette proposition présente différentes possibilités
d’actions sur les informations géographiques,
statistiques et les aspects cartographiques résultent de leur croisement.


### 2.1. Fonctionnement général

3 panneaux etc.

[Arabesque](http://arabesque.ifsttar.fr/) est application web qui se veut dédiée à la visualisation et à l'analyse de flux.

Des fonctionnalités graphiques avancées sont disponibles, que ce soit  pour les nœuds ou les liens.

Arabesque dispose de fonctionnalités de filtrage (numérique, catégoriel, temporel, spatial) avec la 
possibilité de définir ces propres filtres en plus de ceux proposés automatiquement.



### 2.2. Fonctionnement particulier




### 2.3. Technologies





## Partie 3. Exemple d'analyse cartographique




## Conclusion
Les développements actuellement en cours consistent à refactoriser le code initial, suivant présentent un double objectif : stabiliser l'application dans sa construction et dans son fonctionnement et sa maintenance ; préparer une seconde version par l'ajour de fonctionnalités complémentaires ou identifiées comme manquantes. 


**Fundings / financements** : arabesque est développé dans le cade du projet [_geographic flow visualisations (gflowiz)_](https://geoflowiz.hypotheses.org/)
une collaboration interdisciplinaire initiée pour concevoir et développer une nouvelle
application web dédiée à la géo visualisation thématique de données de flux et de réseaux spatiaux.


## References

Bahoken F., Le Campion G., Maisonobe M., Jégou L., Côme É. (2020), « Typologie d’un geoweb des flux et réseaux / Typology of a flow and network geoweb », Géomatica Journal: URL : https://cdnsciencepub.com/doi/abs/10.1139/geomat-2020-0007 ; DOI : 10.1139/geomat-2020-0007.

Le Campion G., Nguyen A. (2019) Dashboard for exploring web applications of geographic flow and movements (DBgFlowiz), IFSTTAR, AME-SPLOTT / COSYS-GRETTIA, and CNRS-UMR Passages. (Accéder)

Jacques Bertin (1973), les diagrammes, les réseaux, les cartes.

Côme E., Bapaume T., Jégou L., Bahoken F., Maisonobe M., Roelandt N., Le Campion G. (2019), Arabesque, application d’exploration et de géovisualisation de données de flux et de réseaux, in: Actes de la conférence internationale de géomatique (SAGEO’2019), Session stockages et flux, Clermont-Ferrand, 13-15 novembre 2019, pp. 265-264. Actes_Sageo2019.

Mac Eachren A., 

Tobler, W. R. (1979), A geographical flow mapping program, Geographical Analysis, n°13, Vol. 1, pp. 1-20.

Tobler W. R. (1982), Cartographic study of movement tables, Presentation in the National Computer, Graphic Assembly – session on Statistical Graphics – Mapping, Anaheim, 17-06-1982.

Roelandt N., Bahoken F., Jégou L., Côme É., Le Campion G. (2020), arabesque : a geographic flow visualization application, FOSDEM’20, Bruxelles [FOSDEM’20 : Session Géospatial Devroom]
